services:
  wordpress:
    image: wordpress:latest
    container_name: ${APP_NAME}-wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${APP_NAME}db
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_NAME}db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  wordpress:
  mysql:
